export const listaSelecoes = [
    {
        name: "Brazil",
        slug: "brazil",
        shortName: "Brazil",
        nameCode: "BRA",
        national: true,
        id: 4748,
        teamColors: {
            primary: "#ffff00",
            secondary: "#009933",
            text: "#009933"
        }
    },
];

export const listaInternacionais = [
    {
        name: "Atlético Madrid",
        slug: "atletico-madrid",
        shortName: "Atl. Madrid",
        nameCode: "ATM",
        id: 2836,
    },
    {
        name: "Barcelona",
        slug: "barcelona",
        shortName: "Barcelona",
        nameCode: "FCB",
        id: 2817,
    },
    {
        name: "Real Madrid",
        slug: "real-madrid",
        shortName: "Real Madrid",
        nameCode: "RMA",
        id: 2829,
    },
    {
        name: "Arsenal",
        slug: "arsenal",
        shortName: "Arsenal",
        nameCode: "ARS",
        id: 42,
    },
    {
        name: "Chelsea",
        slug: "chelsea",
        shortName: "Chelsea",
        nameCode: "CHE",
        id: 38,
    },
    {
        name: "Liverpool",
        slug: "liverpool",
        shortName: "Liverpool",
        nameCode: "LIV",
        id: 44,
    },
    {
        name: "Manchester City",
        slug: "manchester-city",
        shortName: "Man City",
        nameCode: "MCI",
        id: 17,
    },
    {
        name: "Manchester United",
        slug: "manchester-united",
        shortName: "Man Utd",
        nameCode: "MUN",
        id: 35,
    },
    {
        name: "Borussia Dortmund",
        slug: "borussia-dortmund",
        shortName: "Dortmund",
        nameCode: "BVB",
        id: 2673,
    },
    {
        name: "FC Bayern München",
        slug: "fc-bayern-munchen",
        shortName: "Bayern",
        nameCode: "BAY",
        id: 2672,
    },
    {
        name: "Bayer 04 Leverkusen",
        slug: "bayer-04-leverkusen",
        shortName: "Leverkusen",
        nameCode: "B04",
        id: 2681,
    },
    {
        name: "Olympique de Marseille",
        slug: "olympique-de-marseille",
        shortName: "Marseille",
        nameCode: "OM",
        id: 1641,
    },
    {
        name: "Olympique Lyonnais",
        slug: "olympique-lyonnais",
        shortName: "Lyon",
        nameCode: "OL",
        id: 1649,
    },
    {
        name: "Paris Saint-Germain",
        slug: "paris-saint-germain",
        shortName: "PSG",
        nameCode: "PSG",
        id: 1644,
    },
    {
        name: "Inter",
        slug: "inter",
        shortName: "Inter",
        nameCode: "INT",
        id: 2697,
    },
    {
        name: "Juventus",
        slug: "juventus",
        shortName: "Juventus",
        nameCode: "JUV",
        id: 2687,
    },
    {
        name: "Milan",
        slug: "milan",
        shortName: "Milan",
        nameCode: "ACM",
        id: 2692,
    },
    {
        name: "Napoli",
        slug: "napoli",
        shortName: "Napoli",
        nameCode: "NAP",
        id: 2714,
    },
    {
        name: "Roma",
        slug: "roma",
        shortName: "Roma",
        nameCode: "ASR",
        id: 2702,
    },
    {
        name: "Boca Juniors",
        slug: "boca-juniors",
        shortName: "Boca Juniors",
        nameCode: "BOC",
        id: 3202,
    }
];